name: dream_tales_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: COMO
      fonts:
        - asset: assets/fonts/Como-SemiBold.ttf
          weight: 600
          style: normal

  assets:
    - assets/images/logo.png
    - assets/images/home_page_bg.png
    - assets/images/begin_your_story_button_clicked.png
    - assets/images/begin_your_story_button_unclicked.png
    - assets/images/name_page_bg.png
    - assets/images/home_button.png
    - assets/images/next_button_unclicked.png
    - assets/images/next_button_clicked.png
    - assets/images/name_line.png